SET SQLBLANKLINES ON
SET DEFINE OFF

-- Jun 29, 2015 3:51:26 PM BRT
-- Voiding NF-e Numbering
INSERT INTO AD_Process (CopyFromProcess,AD_Process_ID,IsDirectPrint,IsReport,AD_Process_UU,AccessLevel,IsBetaFunctionality,IsServerProcess,Statistic_Seconds,Statistic_Count,ShowHelp,EntityType,Description,Name,AD_Org_ID,UpdatedBy,IsActive,CreatedBy,Classname,Value,AD_Client_ID,Created,Updated) VALUES ('N',800008,'N','N','9ea850f0-68ed-4aa7-8ac5-41c0c22da252','3','N','N',3,3,'Y','LBR','Void NF-e Numbering Sequence','Void NF-e Numbering',0,0,'Y',0,'org.idempierelbr.nfe.process.InutNotaFiscal','LBR_ProcInutNotaFiscal',0,TO_DATE('2015-06-29 15:51:23','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2015-06-29 15:51:23','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 3:55:00 PM BRT
INSERT INTO AD_Process_Para (IsRange,AD_Element_ID,AD_Process_Para_ID,AD_Process_Para_UU,Help,AD_Process_ID,AD_Reference_ID,IsMandatory,Name,ColumnName,Description,FieldLength,IsCentrallyMaintained,SeqNo,DefaultValue,IsActive,UpdatedBy,Updated,CreatedBy,AD_Org_ID,IsEncrypted,AD_Client_ID,AD_Reference_Value_ID,EntityType,Created) VALUES ('N',113,800054,'40de312c-d61a-44d7-9ed4-0f9d03869075','An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.',800008,19,'Y','Organization','AD_Org_ID','Organizational entity within client',10,'Y',10,'-1','Y',0,TO_DATE('2015-06-29 15:54:59','YYYY-MM-DD HH24:MI:SS'),0,0,'N',0,322,'LBR',TO_DATE('2015-06-29 15:54:59','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 3:56:31 PM BRT
INSERT INTO AD_Process_Para (IsRange,AD_Element_ID,AD_Process_Para_ID,AD_Process_Para_UU,AD_Process_ID,AD_Reference_ID,IsMandatory,Name,ColumnName,FieldLength,IsCentrallyMaintained,SeqNo,DefaultValue,IsActive,UpdatedBy,Updated,CreatedBy,AD_Org_ID,IsEncrypted,AD_Client_ID,AD_Reference_Value_ID,EntityType,Created) VALUES ('N',1000234,800055,'51c08245-e9b4-4be6-b7eb-75cf8f440014',800008,17,'Y','Sefaz NF-e Environment','LBR_NFeEnv',1,'Y',20,'-1','Y',0,TO_DATE('2015-06-29 15:56:31','YYYY-MM-DD HH24:MI:SS'),0,0,'N',0,1000051,'LBR',TO_DATE('2015-06-29 15:56:31','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 3:57:33 PM BRT
INSERT INTO AD_Process_Para (IsRange,AD_Element_ID,AD_Process_Para_ID,AD_Process_Para_UU,Help,AD_Process_ID,AD_Reference_ID,IsMandatory,Name,ColumnName,Description,FieldLength,IsCentrallyMaintained,SeqNo,IsActive,UpdatedBy,Updated,CreatedBy,AD_Org_ID,IsEncrypted,AD_Client_ID,EntityType,Created) VALUES ('N',265,800056,'249fed5f-ce24-471e-9fcd-9ba445ba9a97','The Document Date indicates the date the document was generated.  It may or may not be the same as the accounting date.',800008,15,'N','Document Date','DateDoc','Date of the Document',10,'Y',30,'Y',0,TO_DATE('2015-06-29 15:57:32','YYYY-MM-DD HH24:MI:SS'),0,0,'N',0,'LBR',TO_DATE('2015-06-29 15:57:32','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 3:59:25 PM BRT
INSERT INTO AD_Process_Para (IsRange,AD_Element_ID,AD_Process_Para_ID,AD_Process_Para_UU,AD_Process_ID,AD_Reference_ID,IsMandatory,Name,ColumnName,FieldLength,IsCentrallyMaintained,SeqNo,DefaultValue,IsActive,UpdatedBy,Updated,CreatedBy,AD_Org_ID,IsEncrypted,AD_Client_ID,AD_Reference_Value_ID,EntityType,Created) VALUES ('N',1000233,800057,'75f82eac-ddc7-4b1c-9cf1-4179f9ab131a',800008,17,'Y','NFB (DocType) Model','LBR_NFBModel',2,'Y',40,'-1','Y',0,TO_DATE('2015-06-29 15:59:24','YYYY-MM-DD HH24:MI:SS'),0,0,'N',0,1000050,'LBR',TO_DATE('2015-06-29 15:59:24','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 4:01:24 PM BRT
INSERT INTO AD_Process_Para (IsRange,AD_Element_ID,AD_Process_Para_ID,AD_Process_Para_UU,AD_Process_ID,AD_Reference_ID,IsMandatory,Name,ColumnName,FieldLength,IsCentrallyMaintained,SeqNo,IsActive,UpdatedBy,Updated,CreatedBy,AD_Org_ID,IsEncrypted,AD_Client_ID,EntityType,Created) VALUES ('N',1000174,800058,'8a9cdf80-e129-4b59-bbc8-3e5e8eb8a81d',800008,10,'Y','NF Serie','LBR_NFeSerie',3,'Y',50,'Y',0,TO_DATE('2015-06-29 16:01:23','YYYY-MM-DD HH24:MI:SS'),0,0,'N',0,'LBR',TO_DATE('2015-06-29 16:01:23','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 4:02:53 PM BRT
INSERT INTO AD_Process_Para (IsRange,AD_Element_ID,AD_Process_Para_ID,AD_Process_Para_UU,Help,AD_Process_ID,AD_Reference_ID,IsMandatory,Name,ColumnName,Description,FieldLength,IsCentrallyMaintained,SeqNo,IsActive,UpdatedBy,Updated,CreatedBy,AD_Org_ID,IsEncrypted,AD_Client_ID,EntityType,Created) VALUES ('Y',290,800059,'3a559fd6-1959-4bb9-acad-f6d76689d44c','The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).',800008,22,'Y','Document No','DocumentNo','Document sequence number of the document',10,'Y',60,'Y',0,TO_DATE('2015-06-29 16:02:52','YYYY-MM-DD HH24:MI:SS'),0,0,'N',0,'LBR',TO_DATE('2015-06-29 16:02:52','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 4:03:51 PM BRT
INSERT INTO AD_Process_Para (IsRange,AD_Element_ID,AD_Process_Para_ID,AD_Process_Para_UU,AD_Process_ID,AD_Reference_ID,IsMandatory,Name,ColumnName,FieldLength,IsCentrallyMaintained,SeqNo,IsActive,UpdatedBy,Updated,CreatedBy,AD_Org_ID,IsEncrypted,AD_Client_ID,EntityType,Created) VALUES ('N',1000280,800060,'f212c232-04df-46dc-a702-bf7562db3e60',800008,10,'Y','Justification','LBR_Justification',255,'Y',70,'Y',0,TO_DATE('2015-06-29 16:03:51','YYYY-MM-DD HH24:MI:SS'),0,0,'N',0,'LBR',TO_DATE('2015-06-29 16:03:51','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 4:06:53 PM BRT
INSERT INTO AD_Menu (AD_Menu_ID,IsSummary,IsSOTrx,IsReadOnly,AD_Process_ID,EntityType,IsCentrallyMaintained,Name,Description,AD_Menu_UU,Action,IsActive,CreatedBy,Updated,UpdatedBy,AD_Client_ID,AD_Org_ID,Created) VALUES (800006,'N','Y','N',800008,'LBR','Y','Void NF-e Numbering','Void NF-e Numbering Sequence','1476fecb-fee4-4034-9b64-11adc7b791b9','P','Y',0,TO_DATE('2015-06-29 16:06:52','YYYY-MM-DD HH24:MI:SS'),0,0,0,TO_DATE('2015-06-29 16:06:52','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 29, 2015 4:06:53 PM BRT
INSERT INTO AD_TreeNodeMM (AD_Client_ID,AD_Org_ID, IsActive,Created,CreatedBy,Updated,UpdatedBy, AD_Tree_ID, Node_ID, Parent_ID, SeqNo, AD_TreeNodeMM_UU) SELECT t.AD_Client_ID, 0, 'Y', SysDate, 0, SysDate, 0,t.AD_Tree_ID, 800006, 0, 999, Generate_UUID() FROM AD_Tree t WHERE t.AD_Client_ID=0 AND t.IsActive='Y' AND t.IsAllNodes='Y' AND t.TreeType='MM' AND NOT EXISTS (SELECT * FROM AD_TreeNodeMM e WHERE e.AD_Tree_ID=t.AD_Tree_ID AND Node_ID=800006)
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=218
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=1, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=153
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=2, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=263
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=3, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=166
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=4, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=203
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=5, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53242
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=6, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000016
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=7, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=236
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=8, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=183
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=9, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=160
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=10, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=278
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=11, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=345
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=12, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53296
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=13, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53014
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=14, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53108
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000000
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=1, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000017
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=2, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000023
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=3, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000024
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=4, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000021
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=5, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000022
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=6, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800001
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=7, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000035
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=8, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800006
;

-- Jun 29, 2015 4:07:02 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=9, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800000
;

-- Jun 29, 2015 4:12:05 PM BRT
UPDATE AD_Process_Para SET AD_Reference_ID=11,Updated=TO_DATE('2015-06-29 16:12:05','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Process_Para_ID=800059
;

-- Jun 29, 2015 4:18:26 PM BRT
UPDATE AD_Process_Para SET AD_Reference_ID=10,Updated=TO_DATE('2015-06-29 16:18:26','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Process_Para_ID=800059
;

-- Jun 30, 2015 10:03:03 AM BRT
INSERT INTO AD_Table (ImportTable,CopyColumnsFromTable,IsSecurityEnabled,AccessLevel,LoadSeq,AD_Table_ID,IsHighVolume,IsView,IsChangeLog,EntityType,ReplicationType,AD_Table_UU,IsCentrallyMaintained,IsDeleteable,TableName,Description,Name,IsActive,AD_Org_ID,CreatedBy,Updated,UpdatedBy,AD_Client_ID,Processing,DatabaseViewDrop,Created) VALUES ('N','N','N','1',0,800009,'N','N','Y','LBR','L','a29acbcc-20a6-436a-b14f-25b850704e71','Y','Y','LBR_NotaFiscalInut','Identifies a Unused NF-e Numbering','Unused NF-e Numbering','Y',0,0,TO_DATE('2015-06-30 10:03:01','YYYY-MM-DD HH24:MI:SS'),0,0,'N','N',TO_DATE('2015-06-30 10:03:01','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 10:03:04 AM BRT
INSERT INTO AD_Sequence (StartNewYear,CurrentNextSys,IsTableID,CurrentNext,IsAudited,IsAutoSequence,AD_Sequence_ID,Description,Name,IncrementNo,AD_Sequence_UU,CreatedBy,Updated,UpdatedBy,IsActive,StartNo,AD_Client_ID,AD_Org_ID,Created) VALUES ('N',200000,'Y',1000000,'N','Y',800016,'Table LBR_NotaFiscalInut','LBR_NotaFiscalInut',1,'a6e03678-1ca9-4f35-b707-ceb7104988b5',0,TO_DATE('2015-06-30 10:03:03','YYYY-MM-DD HH24:MI:SS'),0,'Y',1000000,0,0,TO_DATE('2015-06-30 10:03:03','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 10:03:58 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,DefaultValue,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Val_Rule_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800539,'N','N','N',0,'N',22,'N','N','N','Y','32925f25-bfe4-49f3-a1a0-48ede3adf0bc','N','AD_Client_ID','Client/Tenant for this installation.','@#AD_Client_ID@','A Client is a company or a legal entity. You cannot share data between Clients. Tenant is a synonym for Client.','Client','N',TO_DATE('2015-06-30 10:03:57','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:03:57','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',102,19,800009,129,0,'LBR')
;

-- Jun 30, 2015 10:04:03 AM BRT
UPDATE AD_Column SET FKConstraintName='ADClient_LBRNotaFiscalInut', FKConstraintType='N',Updated=TO_DATE('2015-06-30 10:04:03','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Column_ID=800539
;

-- Jun 30, 2015 10:04:03 AM BRT
CREATE TABLE LBR_NotaFiscalInut (AD_Client_ID NUMBER(10) DEFAULT NULL )
;

-- Jun 30, 2015 10:04:04 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD CONSTRAINT ADClient_LBRNotaFiscalInut FOREIGN KEY (AD_Client_ID) REFERENCES ad_client(ad_client_id) DEFERRABLE INITIALLY DEFERRED
;

-- Jun 30, 2015 10:05:01 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,DefaultValue,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Val_Rule_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800540,'N','N','N',0,'N',22,'N','N','N','Y','1b4edec3-4181-45d2-a43d-dd1a96d2b58b','N','AD_Org_ID','Organizational entity within client','@#AD_Org_ID@','An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.','Organization','N',TO_DATE('2015-06-30 10:05:01','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:05:01','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',113,19,800009,104,0,'LBR')
;

-- Jun 30, 2015 10:05:04 AM BRT
UPDATE AD_Column SET FKConstraintName='ADOrg_LBRNotaFiscalInut', FKConstraintType='N',Updated=TO_DATE('2015-06-30 10:05:04','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Column_ID=800540
;

-- Jun 30, 2015 10:05:04 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD AD_Org_ID NUMBER(10) DEFAULT NULL 
;

-- Jun 30, 2015 10:05:04 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD CONSTRAINT ADOrg_LBRNotaFiscalInut FOREIGN KEY (AD_Org_ID) REFERENCES ad_org(ad_org_id) DEFERRABLE INITIALLY DEFERRED
;

-- Jun 30, 2015 10:05:33 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,DefaultValue,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800541,'N','N','N',0,'N',7,'N','N','N','Y','60004451-3392-4f9a-b497-7f951fb2d1f6','N','Created','Date this record was created','SYSDATE','The Created field indicates the date that this record was created.','Created','N',TO_DATE('2015-06-30 10:05:32','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:05:32','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',245,16,800009,0,'LBR')
;

-- Jun 30, 2015 10:05:35 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD Created DATE DEFAULT SYSDATE
;

-- Jun 30, 2015 10:05:55 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Reference_Value_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800542,'N','N','N',0,'N',22,'N','N','N','Y','66a363a4-4826-4563-bbb7-987101ca9649','N','CreatedBy','User who created this records','The Created By field indicates the user who created this record.','Created By','N',TO_DATE('2015-06-30 10:05:54','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:05:54','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',246,18,110,800009,0,'LBR')
;

-- Jun 30, 2015 10:05:58 AM BRT
UPDATE AD_Column SET FKConstraintName='CreatedBy_LBRNotaFiscalInut', FKConstraintType='N',Updated=TO_DATE('2015-06-30 10:05:58','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Column_ID=800542
;

-- Jun 30, 2015 10:05:58 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD CreatedBy NUMBER(10) DEFAULT NULL 
;

-- Jun 30, 2015 10:05:58 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD CONSTRAINT CreatedBy_LBRNotaFiscalInut FOREIGN KEY (CreatedBy) REFERENCES ad_user(ad_user_id) DEFERRABLE INITIALLY DEFERRED
;

-- Jun 30, 2015 10:06:24 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,DefaultValue,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800543,'N','N','N',0,'N',7,'N','N','N','Y','31cb85df-cbee-43d5-9741-b8d8fdbd573c','N','Updated','Date this record was updated','SYSDATE','The Updated field indicates the date that this record was updated.','Updated','N',TO_DATE('2015-06-30 10:06:24','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:06:24','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',607,16,800009,0,'LBR')
;

-- Jun 30, 2015 10:06:27 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD Updated DATE DEFAULT SYSDATE
;

-- Jun 30, 2015 10:06:55 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Reference_Value_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800544,'N','N','N',0,'N',22,'N','N','N','Y','4ffe611e-1d48-4351-a653-068d3135eeeb','N','UpdatedBy','User who updated this records','The Updated By field indicates the user who updated this record.','Updated By','N',TO_DATE('2015-06-30 10:06:54','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:06:54','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',608,18,110,800009,0,'LBR')
;

-- Jun 30, 2015 10:06:57 AM BRT
UPDATE AD_Column SET FKConstraintName='UpdatedBy_LBRNotaFiscalInut', FKConstraintType='N',Updated=TO_DATE('2015-06-30 10:06:57','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Column_ID=800544
;

-- Jun 30, 2015 10:06:57 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD UpdatedBy NUMBER(10) DEFAULT NULL 
;

-- Jun 30, 2015 10:06:57 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD CONSTRAINT UpdatedBy_LBRNotaFiscalInut FOREIGN KEY (UpdatedBy) REFERENCES ad_user(ad_user_id) DEFERRABLE INITIALLY DEFERRED
;

-- Jun 30, 2015 10:07:27 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,DefaultValue,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800545,'N','N','N',0,'N',1,'N','N','N','Y','0ef6f0bc-f4ef-4b7b-a1b2-d347d43eb927','Y','IsActive','The record is active in the system','Y','There are two methods of making records unavailable in the system: One is to delete the record, the other is to de-activate the record. A de-activated record is not available for selection, but available for reports.
There are two reasons for de-activating and not deleting records:
(1) The system requires the record for audit purposes.
(2) The record is referenced by other records. E.g., you cannot delete a Business Partner, if there are invoices for this partner record existing. You de-activate the Business Partner and prevent that this record is used for future entries.','Active','N',TO_DATE('2015-06-30 10:07:26','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:07:26','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',348,20,800009,0,'LBR')
;

-- Jun 30, 2015 10:07:29 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N'))
;

-- Jun 30, 2015 10:09:16 AM BRT
INSERT INTO AD_Element (ColumnName,AD_Element_ID,Name,Description,PrintName,AD_Element_UU,AD_Org_ID,CreatedBy,UpdatedBy,IsActive,AD_Client_ID,EntityType,Created,Updated) VALUES ('LBR_NotaFiscalInut_ID',800110,'Unused NF-e Numbering','Identifies a Unused NF-e Numbering','Unused NF-e Numbering','c3bbeae8-fd8c-45cb-a003-1e272dfc1ada',0,0,0,'Y',0,'LBR',TO_DATE('2015-06-30 10:09:16','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2015-06-30 10:09:16','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 10:09:38 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800546,'N','N','N',0,'N',22,'N','Y','N','Y','13feda4f-86d2-4ddb-99d2-4782e5cba7e9','N','LBR_NotaFiscalInut_ID','Identifies a Unused NF-e Numbering','Unused NF-e Numbering','N',TO_DATE('2015-06-30 10:09:37','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:09:37','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',800110,13,800009,0,'LBR')
;

-- Jun 30, 2015 10:09:40 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_NotaFiscalInut_ID NUMBER(10) DEFAULT NULL 
;

-- Jun 30, 2015 10:09:40 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD CONSTRAINT LBR_NotaFiscalInut_Key PRIMARY KEY (LBR_NotaFiscalInut_ID)
;

-- Jun 30, 2015 10:10:10 AM BRT
INSERT INTO AD_Element (ColumnName,AD_Element_ID,Name,Description,PrintName,AD_Element_UU,AD_Org_ID,CreatedBy,UpdatedBy,IsActive,AD_Client_ID,EntityType,Created,Updated) VALUES ('LBR_NotaFiscalInut_UU',800111,'Unused NF-e Numbering','Identifies a Unused NF-e Numbering','Unused NF-e Numbering','4fd954a8-3aa8-47fb-847a-830ce0aa2abd',0,0,0,'Y',0,'LBR',TO_DATE('2015-06-30 10:10:10','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2015-06-30 10:10:10','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 10:10:45 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800547,'N','N','N',0,'N',36,'N','N','N','Y','a36a44e6-1bf8-4583-b7f7-93c41bddb983','N','LBR_NotaFiscalInut_UU','Identifies a Unused NF-e Numbering','Unused NF-e Numbering','N',TO_DATE('2015-06-30 10:10:44','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:10:44','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',800111,10,800009,0,'LBR')
;

-- Jun 30, 2015 10:10:48 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_NotaFiscalInut_UU NVARCHAR2(36) DEFAULT NULL 
;

-- Jun 30, 2015 10:10:48 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD CONSTRAINT LBR_NotaFiscalInut_UU_idx UNIQUE (LBR_NotaFiscalInut_UU)
;

-- Jun 30, 2015 10:12:04 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800548,'N','N','N',0,'N',255,'Y','N','N','Y','68af6373-f155-43d9-bc81-ef6d4d9985e0','Y','Description','Optional short description of the record','A description is limited to 255 characters.','Description','Y',TO_DATE('2015-06-30 10:12:03','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:12:03','YYYY-MM-DD HH24:MI:SS'),0,'N','Y',0,'N','N',275,10,800009,0,'LBR')
;

-- Jun 30, 2015 10:12:07 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD Description NVARCHAR2(255) DEFAULT NULL 
;

-- Jun 30, 2015 10:13:16 AM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800549,'Y','N','N',0,'N',30,'Y','N','N','Y','01dc01f6-186f-4495-9652-947b135e5cb1','N','DocumentNo','Document sequence number of the document','The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).','Document No','Y',TO_DATE('2015-06-30 10:13:15','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 10:13:15','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',290,10,800009,0,'LBR')
;

-- Jun 30, 2015 10:13:18 AM BRT
ALTER TABLE LBR_NotaFiscalInut ADD DocumentNo NVARCHAR2(30) NOT NULL
;

-- Jun 30, 2015 1:21:41 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,FKConstraintType,AD_Element_ID,AD_Reference_ID,AD_Reference_Value_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800550,'Y','N','N',0,'N',1,'N','N','N','Y','01718010-8941-44c5-8255-81f2055a37d2','Y','LBR_NFeEnv','Sefaz NF-e Environment','Y',TO_DATE('2015-06-30 13:21:37','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:21:37','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N','N',1000234,17,1000051,800009,0,'LBR')
;

-- Jun 30, 2015 1:21:45 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_NFeEnv CHAR(1) NOT NULL
;

-- Jun 30, 2015 1:23:15 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,FKConstraintType,AD_Element_ID,AD_Reference_ID,AD_Reference_Value_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800551,'N','N','N',0,'N',3,'N','N','N','Y','7c389586-3138-4e85-986a-3ae576c3a753','Y','LBR_LotSendingStatus','Indicates the status of the sending process to Sefaz','NF-e Lot Sending Status','Y',TO_DATE('2015-06-30 13:23:14','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:23:14','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N','N',1000267,17,1000039,800009,0,'LBR')
;

-- Jun 30, 2015 1:23:18 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_LotSendingStatus NVARCHAR2(3) DEFAULT NULL 
;

-- Jun 30, 2015 1:25:18 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,DefaultValue,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800552,'N','N','N',0,'N',7,'N','N','N','Y','503176ed-7eca-4561-98ff-5cfeb5a36eb1','Y','DateDoc','Date of the Document','@#Date@','The Document Date indicates the date the document was generated.  It may or may not be the same as the accounting date.','Document Date','Y',TO_DATE('2015-06-30 13:25:17','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:25:17','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',265,15,800009,0,'LBR')
;

-- Jun 30, 2015 1:25:26 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD DateDoc DATE DEFAULT NULL 
;

-- Jun 30, 2015 1:26:00 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,FKConstraintType,AD_Element_ID,AD_Reference_ID,AD_Reference_Value_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800553,'Y','N','N',0,'N',2,'N','N','N','Y','a635ecca-d212-471f-8b1a-e65fef83b58d','Y','LBR_NFBModel','NFB (DocType) Model','Y',TO_DATE('2015-06-30 13:25:59','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:25:59','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N','N',1000233,17,1000050,800009,0,'LBR')
;

-- Jun 30, 2015 1:26:02 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_NFBModel NVARCHAR2(2) NOT NULL
;

-- Jun 30, 2015 1:27:40 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,FKConstraintType,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800554,'Y','N','N',0,'N',3,'N','N','N','Y','fc0fda43-25b1-44d7-8c25-80336f242a45','Y','LBR_NFeSerie','NF Serie','Y',TO_DATE('2015-06-30 13:27:39','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:27:39','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N','N',1000174,10,800009,0,'LBR')
;

-- Jun 30, 2015 1:27:44 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_NFeSerie NVARCHAR2(3) NOT NULL
;

-- Jun 30, 2015 1:32:03 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,FKConstraintType,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800555,'N','N','N',0,'N',7,'N','N','N','Y','0fae2012-079c-4853-9000-e77a3a8d7c31','Y','LBR_LotSentOn','The date+time (expressed in decimal format) when the NF-e Lot has been sent','NF-e Lot Sent On','Y',TO_DATE('2015-06-30 13:32:02','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:32:02','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N','N',1000259,16,800009,0,'LBR')
;

-- Jun 30, 2015 1:32:06 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_LotSentOn DATE DEFAULT NULL 
;

-- Jun 30, 2015 1:32:49 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,FKConstraintType,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800556,'N','N','N',0,'N',255,'N','N','N','Y','570bb7fb-3cba-4923-917a-801deb89bb64','Y','LBR_LotSendingProt','Indicates the protocol of the sending process to Sefaz','NF-e Lot Sending Protocol','Y',TO_DATE('2015-06-30 13:32:49','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:32:49','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N','N',1000270,10,800009,0,'LBR')
;

-- Jun 30, 2015 1:32:52 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_LotSendingProt NVARCHAR2(255) DEFAULT NULL 
;

-- Jun 30, 2015 1:33:34 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,MandatoryLogic,AD_Column_UU,IsUpdateable,ColumnName,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,FKConstraintType,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800557,'N','N','N',0,'N',255,'N','N','N','Y','@LBR_NFeEventType@=''CAN''','59d25aa3-d4c5-4026-872b-268d7d5e5ec1','Y','LBR_Justification','Justification','Y',TO_DATE('2015-06-30 13:33:32','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:33:32','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N','N',1000280,14,800009,0,'LBR')
;

-- Jun 30, 2015 1:33:44 PM BRT
UPDATE AD_Column SET MandatoryLogic=NULL,Updated=TO_DATE('2015-06-30 13:33:44','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Column_ID=800557
;

-- Jun 30, 2015 1:33:47 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_Justification NVARCHAR2(255) DEFAULT NULL 
;

-- Jun 30, 2015 1:35:12 PM BRT
INSERT INTO AD_Element (ColumnName,AD_Element_ID,Name,Description,PrintName,AD_Element_UU,AD_Org_ID,CreatedBy,UpdatedBy,IsActive,AD_Client_ID,EntityType,Created,Updated) VALUES ('LBR_Number_Start',800112,'Number (Start)','Indicates the start number','Number (Start)','2d55b716-37ca-41fc-a200-eb273f29d51c',0,0,0,'Y',0,'LBR',TO_DATE('2015-06-30 13:35:11','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2015-06-30 13:35:11','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 1:35:56 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800558,'Y','N','N',0,'N',9,'N','N','N','Y','3935ea02-1879-4dd8-8db3-2843dc9f7fd9','Y','LBR_Number_Start','Indicates the start number','Number (Start)','Y',TO_DATE('2015-06-30 13:35:55','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:35:55','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',800112,10,800009,0,'LBR')
;

-- Jun 30, 2015 1:35:59 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_Number_Start NVARCHAR2(9) NOT NULL
;

-- Jun 30, 2015 1:36:45 PM BRT
INSERT INTO AD_Element (ColumnName,AD_Element_ID,Name,Description,PrintName,AD_Element_UU,AD_Org_ID,CreatedBy,UpdatedBy,IsActive,AD_Client_ID,EntityType,Created,Updated) VALUES ('LBR_Number_End',800113,'Number (End)','Indicates the end number','Number (End)','3408e848-9839-4fe8-bac3-462569d4c98f',0,0,0,'Y',0,'LBR',TO_DATE('2015-06-30 13:36:44','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2015-06-30 13:36:44','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 1:37:21 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800559,'Y','N','N',0,'N',9,'N','N','N','Y','c059a9bb-aaf1-4151-b940-a96025c9c4fa','Y','LBR_Number_End','Indicates the end number','Number (End)','Y',TO_DATE('2015-06-30 13:37:20','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-06-30 13:37:20','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',800113,10,800009,0,'LBR')
;

-- Jun 30, 2015 1:37:24 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD LBR_Number_End NVARCHAR2(9) NOT NULL
;

-- Jun 30, 2015 2:10:54 PM BRT
INSERT INTO AD_Window (Processing,WindowType,Help,IsSOTrx,IsDefault,IsBetaFunctionality,WinHeight,WinWidth,EntityType,Name,Description,AD_Window_ID,AD_Window_UU,Updated,AD_Org_ID,IsActive,UpdatedBy,CreatedBy,AD_Client_ID,Created) VALUES ('N','T','The Unused Brazilian Fiscal Invoice Numbering Window allows tracking all registered (Sefaz) unused numbering.','Y','N','N',0,0,'LBR','Unused Brazilian Fiscal Invoice Numbering (LBR)','Unused Brazilian Fiscal Invoice Numbering',800001,'a48dd080-f858-42cb-80c9-2d248bf32072',TO_DATE('2015-06-30 14:10:54','YYYY-MM-DD HH24:MI:SS'),0,'Y',0,0,0,TO_DATE('2015-06-30 14:10:54','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:12:58 PM BRT
INSERT INTO AD_Tab (ImportFields,Processing,IsSingleRow,AD_Window_ID,SeqNo,IsTranslationTab,IsSortTab,HasTree,IsInfoTab,IsReadOnly,IsInsertRecord,IsAdvancedTab,TabLevel,AD_Tab_UU,EntityType,Name,Description,AD_Tab_ID,AD_Org_ID,CreatedBy,Updated,UpdatedBy,IsActive,AD_Client_ID,AD_Table_ID,TreeDisplayedOn,Created) VALUES ('N','N','N',800001,10,'N','N','N','N','N','N','N',0,'cdeb187c-c51f-4a09-ba9d-dc70da0e22da','LBR','NF-e Unused Numbering','NF-e Unused Numbering Entries',800007,0,0,TO_DATE('2015-06-30 14:12:57','YYYY-MM-DD HH24:MI:SS'),0,'Y',0,800009,'B',TO_DATE('2015-06-30 14:12:57','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:12 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,Help,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,22,'N','N',10,'Y',800103,'N','A Client is a company or a legal entity. You cannot share data between Clients. Tenant is a synonym for Client.','LBR','Client/Tenant for this installation.','Client','e4ce7361-e7a1-4ce5-87bf-adbb521ca362','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:12','YYYY-MM-DD HH24:MI:SS'),'Y','N',0,2,800539,TO_DATE('2015-06-30 14:13:12','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:13 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,Help,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,IsAllowCopy,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,XPosition,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,22,'N','N',20,'Y',800104,'N','An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.','LBR','Organizational entity within client','Organization','f66cea51-5abe-40d2-8906-f7061c42b248','N','Y','Y',0,0,0,TO_DATE('2015-06-30 14:13:13','YYYY-MM-DD HH24:MI:SS'),'Y','Y',10,4,0,2,800540,TO_DATE('2015-06-30 14:13:13','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:14 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,Help,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,255,'N','N',30,'Y',800105,'N','A description is limited to 255 characters.','LBR','Optional short description of the record','Description','02b85f3f-67de-4411-a92b-76c5f2b4e38e','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:13','YYYY-MM-DD HH24:MI:SS'),'Y','Y',20,0,5,800548,TO_DATE('2015-06-30 14:13:13','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:15 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,22,'N','N','Y',800106,'N','LBR','Identifies a Unused NF-e Numbering','Unused NF-e Numbering','081c3108-a285-41b5-861b-f778124a882f','N','N',0,0,0,TO_DATE('2015-06-30 14:13:14','YYYY-MM-DD HH24:MI:SS'),'Y','N',0,2,800546,TO_DATE('2015-06-30 14:13:14','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:16 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,36,'N','N',40,'Y',800107,'N','LBR','Identifies a Unused NF-e Numbering','Unused NF-e Numbering','c697038f-a218-46c4-9bc0-e2dc7a175f34','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:15','YYYY-MM-DD HH24:MI:SS'),'Y','Y',30,0,2,800547,TO_DATE('2015-06-30 14:13:15','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:17 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,Help,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,30,'N','N',50,'Y',800108,'N','The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).','LBR','Document sequence number of the document','Document No','8381790b-4a99-4f59-8b72-3c4000d49b19','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:16','YYYY-MM-DD HH24:MI:SS'),'Y','Y',40,0,2,800549,TO_DATE('2015-06-30 14:13:16','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:18 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,1,'N','N',60,'Y',800109,'N','LBR','Sefaz NF-e Environment','d15d68f3-0f7e-4be2-b357-b9981455259b','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:17','YYYY-MM-DD HH24:MI:SS'),'Y','Y',50,0,2,800550,TO_DATE('2015-06-30 14:13:17','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:19 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,3,'N','N',70,'Y',800110,'N','LBR','Indicates the status of the sending process to Sefaz','NF-e Lot Sending Status','7214d961-ed7c-4db1-8996-ac9096e3d4bd','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:18','YYYY-MM-DD HH24:MI:SS'),'Y','Y',60,0,2,800551,TO_DATE('2015-06-30 14:13:18','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:20 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,Help,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,7,'N','N',80,'Y',800111,'N','The Document Date indicates the date the document was generated.  It may or may not be the same as the accounting date.','LBR','Date of the Document','Document Date','b619c1c9-a1ba-4520-8e04-3d618762fab1','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:19','YYYY-MM-DD HH24:MI:SS'),'Y','Y',70,0,2,800552,TO_DATE('2015-06-30 14:13:19','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:20 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,2,'N','N',90,'Y',800112,'N','LBR','NFB (DocType) Model','d5669e1b-99bb-4c6b-a2ed-fb32d827b00b','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:20','YYYY-MM-DD HH24:MI:SS'),'Y','Y',80,0,2,800553,TO_DATE('2015-06-30 14:13:20','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:21 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,3,'N','N',100,'Y',800113,'N','LBR','NF Serie','3ffba995-a1b6-422e-a563-dac49e231f17','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:20','YYYY-MM-DD HH24:MI:SS'),'Y','Y',90,0,2,800554,TO_DATE('2015-06-30 14:13:20','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:22 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,7,'N','N',110,'Y',800114,'N','LBR','The date+time (expressed in decimal format) when the NF-e Lot has been sent','NF-e Lot Sent On','61d91c8a-33ed-4235-bbd0-d7506bf5dd6b','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:21','YYYY-MM-DD HH24:MI:SS'),'Y','Y',100,0,2,800555,TO_DATE('2015-06-30 14:13:21','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:23 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,255,'N','N',120,'Y',800115,'N','LBR','Indicates the protocol of the sending process to Sefaz','NF-e Lot Sending Protocol','073e932c-0db7-44c5-8b79-73f17d8ee957','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:22','YYYY-MM-DD HH24:MI:SS'),'Y','Y',110,0,5,800556,TO_DATE('2015-06-30 14:13:22','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:24 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,NumLines,AD_Column_ID,Created) VALUES ('N',800007,255,'N','N',130,'Y',800116,'N','LBR','Justification','0d9e1031-66e5-47b0-8405-a01d734f4638','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:23','YYYY-MM-DD HH24:MI:SS'),'Y','Y',120,0,5,3,800557,TO_DATE('2015-06-30 14:13:23','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:25 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,9,'N','N',140,'Y',800117,'N','LBR','Indicates the start number','Number (Start)','707cbccb-9bd9-4679-90f2-dc4f032b1271','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:24','YYYY-MM-DD HH24:MI:SS'),'Y','Y',130,0,2,800558,TO_DATE('2015-06-30 14:13:24','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:26 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,9,'N','N',150,'Y',800118,'N','LBR','Indicates the end number','Number (End)','86da7a0b-c7d6-4467-a1d3-8a66d353d1c8','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:25','YYYY-MM-DD HH24:MI:SS'),'Y','Y',140,0,2,800559,TO_DATE('2015-06-30 14:13:25','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:13:27 PM BRT
INSERT INTO AD_Field (IsEncrypted,AD_Tab_ID,DisplayLength,IsSameLine,IsHeading,SeqNo,IsCentrallyMaintained,AD_Field_ID,IsReadOnly,Help,EntityType,Description,Name,AD_Field_UU,IsFieldOnly,IsDisplayed,UpdatedBy,AD_Org_ID,CreatedBy,Updated,IsActive,IsDisplayedGrid,SeqNoGrid,XPosition,AD_Client_ID,ColumnSpan,AD_Column_ID,Created) VALUES ('N',800007,1,'N','N',160,'Y',800119,'N','There are two methods of making records unavailable in the system: One is to delete the record, the other is to de-activate the record. A de-activated record is not available for selection, but available for reports.
There are two reasons for de-activating and not deleting records:
(1) The system requires the record for audit purposes.
(2) The record is referenced by other records. E.g., you cannot delete a Business Partner, if there are invoices for this partner record existing. You de-activate the Business Partner and prevent that this record is used for future entries.','LBR','The record is active in the system','Active','44be1d35-193a-4517-b22a-39fbbf19f463','N','Y',0,0,0,TO_DATE('2015-06-30 14:13:26','YYYY-MM-DD HH24:MI:SS'),'Y','Y',150,2,0,2,800545,TO_DATE('2015-06-30 14:13:26','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:14:29 PM BRT
UPDATE AD_Table SET AD_Window_ID=800001, IsDeleteable='N',Updated=TO_DATE('2015-06-30 14:14:29','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Table_ID=800009
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=0,IsDisplayed='N' WHERE AD_Field_ID=800107
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=30,IsDisplayed='Y' WHERE AD_Field_ID=800108
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=40,IsDisplayed='Y' WHERE AD_Field_ID=800105
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=50,IsDisplayed='Y' WHERE AD_Field_ID=800119
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=70,IsDisplayed='Y' WHERE AD_Field_ID=800111
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=80,IsDisplayed='Y' WHERE AD_Field_ID=800112
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=90,IsDisplayed='Y' WHERE AD_Field_ID=800113
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=100,IsDisplayed='Y' WHERE AD_Field_ID=800117
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=110,IsDisplayed='Y' WHERE AD_Field_ID=800118
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=120,IsDisplayed='Y' WHERE AD_Field_ID=800116
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=130,IsDisplayed='Y' WHERE AD_Field_ID=800110
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=140,IsDisplayed='Y' WHERE AD_Field_ID=800114
;

-- Jun 30, 2015 2:16:40 PM BRT
UPDATE AD_Field SET SeqNo=150,IsDisplayed='Y' WHERE AD_Field_ID=800115
;

-- Jun 30, 2015 2:17:19 PM BRT
UPDATE AD_Field SET NumLines=3,Updated=TO_DATE('2015-06-30 14:17:19','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Field_ID=800105
;

-- Jun 30, 2015 2:17:47 PM BRT
UPDATE AD_Field SET XPosition=4,Updated=TO_DATE('2015-06-30 14:17:47','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Field_ID=800113
;

-- Jun 30, 2015 2:17:56 PM BRT
UPDATE AD_Field SET XPosition=4,Updated=TO_DATE('2015-06-30 14:17:56','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Field_ID=800118
;

-- Jun 30, 2015 2:18:18 PM BRT
UPDATE AD_Field SET ColumnSpan=5,Updated=TO_DATE('2015-06-30 14:18:18','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Field_ID=800110
;

-- Jun 30, 2015 2:18:52 PM BRT
UPDATE AD_Field SET XPosition=4, ColumnSpan=2,Updated=TO_DATE('2015-06-30 14:18:52','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Field_ID=800115
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=0,IsDisplayedGrid='N' WHERE AD_Field_ID=800107
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=30,IsDisplayedGrid='Y' WHERE AD_Field_ID=800108
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=40,IsDisplayedGrid='Y' WHERE AD_Field_ID=800111
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=50,IsDisplayedGrid='Y' WHERE AD_Field_ID=800118
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=60,IsDisplayedGrid='Y' WHERE AD_Field_ID=800117
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=70,IsDisplayedGrid='Y' WHERE AD_Field_ID=800116
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=80,IsDisplayedGrid='Y' WHERE AD_Field_ID=800110
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=90,IsDisplayedGrid='Y' WHERE AD_Field_ID=800114
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=100,IsDisplayedGrid='Y' WHERE AD_Field_ID=800115
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=110,IsDisplayedGrid='Y' WHERE AD_Field_ID=800109
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=120,IsDisplayedGrid='Y' WHERE AD_Field_ID=800112
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=130,IsDisplayedGrid='Y' WHERE AD_Field_ID=800113
;

-- Jun 30, 2015 2:20:12 PM BRT
UPDATE AD_Field SET SeqNoGrid=140,IsDisplayedGrid='Y' WHERE AD_Field_ID=800119
;

-- Jun 30, 2015 2:21:10 PM BRT
INSERT INTO AD_Menu (AD_Window_ID,AD_Menu_ID,IsSummary,IsSOTrx,IsReadOnly,EntityType,IsCentrallyMaintained,Name,Description,AD_Menu_UU,Action,IsActive,CreatedBy,Updated,UpdatedBy,AD_Client_ID,AD_Org_ID,Created) VALUES (800001,800007,'N','Y','N','LBR','Y','Unused Brazilian Fiscal Invoice Numbering (LBR)','Unused Brazilian Fiscal Invoice Numbering','f1f49c33-1b5f-46b8-8c0c-91893b269448','W','Y',0,TO_DATE('2015-06-30 14:21:09','YYYY-MM-DD HH24:MI:SS'),0,0,0,TO_DATE('2015-06-30 14:21:09','YYYY-MM-DD HH24:MI:SS'))
;

-- Jun 30, 2015 2:21:10 PM BRT
INSERT INTO AD_TreeNodeMM (AD_Client_ID,AD_Org_ID, IsActive,Created,CreatedBy,Updated,UpdatedBy, AD_Tree_ID, Node_ID, Parent_ID, SeqNo, AD_TreeNodeMM_UU) SELECT t.AD_Client_ID, 0, 'Y', SysDate, 0, SysDate, 0,t.AD_Tree_ID, 800007, 0, 999, Generate_UUID() FROM AD_Tree t WHERE t.AD_Client_ID=0 AND t.IsActive='Y' AND t.IsAllNodes='Y' AND t.TreeType='MM' AND NOT EXISTS (SELECT * FROM AD_TreeNodeMM e WHERE e.AD_Tree_ID=t.AD_Tree_ID AND Node_ID=800007)
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=218
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=1, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=153
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=2, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=263
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=3, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=166
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=4, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=203
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=5, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53242
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=6, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000016
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=7, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=236
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=8, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=183
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=9, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=160
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=10, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=278
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=11, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=345
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=12, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53296
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=13, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53014
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=0, SeqNo=14, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=53108
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000000
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=1, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000017
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=2, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000023
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=3, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000024
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=4, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000021
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=5, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000022
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=6, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800001
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=7, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000035
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=8, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800006
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=9, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800000
;

-- Jun 30, 2015 2:21:15 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=10, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800007
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000000
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=1, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000017
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=2, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000023
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=3, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000024
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=4, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000021
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=5, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000022
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=6, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800001
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=7, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=1000035
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=8, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800006
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=9, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800007
;

-- Jun 30, 2015 2:21:20 PM BRT
UPDATE AD_TreeNodeMM SET Parent_ID=1000016, SeqNo=10, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=800000
;

-- Jun 30, 2015 2:23:06 PM BRT
UPDATE AD_Field SET SeqNoGrid=50,IsDisplayedGrid='Y' WHERE AD_Field_ID=800117
;

-- Jun 30, 2015 2:23:06 PM BRT
UPDATE AD_Field SET SeqNoGrid=60,IsDisplayedGrid='Y' WHERE AD_Field_ID=800118
;

-- Jul 1, 2015 2:06:14 PM BRT
INSERT INTO AD_Column (SeqNoSelection,IsSyncDatabase,Version,AD_Column_ID,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsParent,FieldLength,IsSelectionColumn,IsKey,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsUpdateable,ColumnName,Description,Help,Name,IsAllowCopy,Updated,CreatedBy,IsActive,Created,UpdatedBy,IsToolbarButton,IsAlwaysUpdateable,AD_Client_ID,IsEncrypted,IsSecure,AD_Element_ID,AD_Reference_ID,AD_Table_ID,AD_Org_ID,EntityType) VALUES (0,'N',0,800560,'N','N','N',0,'N',1,'N','N','N','Y','4948e391-a9e2-4770-b581-d38e48b129d4','Y','Processed','The document has been processed','The Processed checkbox indicates that a document has been processed.','Processed','Y',TO_DATE('2015-07-01 14:06:08','YYYY-MM-DD HH24:MI:SS'),0,'Y',TO_DATE('2015-07-01 14:06:08','YYYY-MM-DD HH24:MI:SS'),0,'N','N',0,'N','N',1047,20,800009,0,'LBR')
;

-- Jul 1, 2015 2:06:16 PM BRT
ALTER TABLE LBR_NotaFiscalInut ADD Processed CHAR(1) DEFAULT NULL  CHECK (Processed IN ('Y','N'))
;

-- Jul 1, 2015 2:12:22 PM BRT
UPDATE AD_Tab SET IsReadOnly='Y',Updated=TO_DATE('2015-07-01 14:12:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Tab_ID=800007
;

SELECT lbr_register_migration_script('201506291551.sql') FROM dual
;
