-- Correcoes do MDF-e apuradas pelos testes
SELECT register_migration_script('202609081440_LBRMDFeCorrecoes.sql') FROM dual;

SET SQLBLANKLINES ON
SET DEFINE OFF


--1. as 20 FKs que faltaram

-- 8 de set. de 2026 15:00:09 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeAutXML', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:00:09','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802646
;

ALTER TABLE LBR_MDFeAutXML ADD CONSTRAINT LBRMDFe_LBRMDFeAutXML FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:00:18 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFeSeg_LBRMDFeAverb', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:00:18','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802634
;

ALTER TABLE LBR_MDFeAverb ADD CONSTRAINT LBRMDFeSeg_LBRMDFeAverb FOREIGN KEY (LBR_MDFeSeg_ID) REFERENCES LBR_MDFeSeg(LBR_MDFeSeg_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:00:27 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeCIOT', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:00:27','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802515
;

ALTER TABLE LBR_MDFeCIOT ADD CONSTRAINT LBRMDFe_LBRMDFeCIOT FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:00:36 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFeInfPag_LBRMDFeComp', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:00:36','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802589
;

ALTER TABLE LBR_MDFeComp ADD CONSTRAINT LBRMDFeInfPag_LBRMDFeComp FOREIGN KEY (LBR_MDFeInfPag_ID) REFERENCES LBR_MDFeInfPag(LBR_MDFeInfPag_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:00:45 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeCondutor', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:00:45','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802413
;

ALTER TABLE LBR_MDFeCondutor ADD CONSTRAINT LBRMDFe_LBRMDFeCondutor FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:00:54 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeContratante', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:00:54','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802546
;

ALTER TABLE LBR_MDFeContratante ADD CONSTRAINT LBRMDFe_LBRMDFeContratante FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:01:03 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFeMunDescarga_LBRMDFeDoc', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:01:03','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802480
;

ALTER TABLE LBR_MDFeDoc ADD CONSTRAINT LBRMDFeMunDescarga_LBRMDFeDoc FOREIGN KEY (LBR_MDFeMunDescarga_ID) REFERENCES LBR_MDFeMunDescarga(LBR_MDFeMunDescarga_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:01:12 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeEvento', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:01:12','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802660
;

ALTER TABLE LBR_MDFeEvento ADD CONSTRAINT LBRMDFe_LBRMDFeEvento FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:01:21 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeInfPag', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:01:21','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802564
;

ALTER TABLE LBR_MDFeInfPag ADD CONSTRAINT LBRMDFe_LBRMDFeInfPag FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:01:30 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeLacre', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:01:30','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802453
;

ALTER TABLE LBR_MDFeLacre ADD CONSTRAINT LBRMDFe_LBRMDFeLacre FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:01:39 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeMunCarrega', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:01:39','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802387
;

ALTER TABLE LBR_MDFeMunCarrega ADD CONSTRAINT LBRMDFe_LBRMDFeMunCarrega FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:01:48 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeMunDescarga', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:01:48','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802466
;

ALTER TABLE LBR_MDFeMunDescarga ADD CONSTRAINT LBRMDFe_LBRMDFeMunDescarga FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:01:57 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFePercurso', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:01:57','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802401
;

ALTER TABLE LBR_MDFePercurso ADD CONSTRAINT LBRMDFe_LBRMDFePercurso FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:02:06 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFeDoc_LBRMDFePerigoso', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:02:06','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802498
;

ALTER TABLE LBR_MDFePerigoso ADD CONSTRAINT LBRMDFeDoc_LBRMDFePerigoso FOREIGN KEY (LBR_MDFeDoc_ID) REFERENCES LBR_MDFeDoc(LBR_MDFeDoc_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:02:15 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFeInfPag_LBRMDFePrazo', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:02:15','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802603
;

ALTER TABLE LBR_MDFePrazo ADD CONSTRAINT LBRMDFeInfPag_LBRMDFePrazo FOREIGN KEY (LBR_MDFeInfPag_ID) REFERENCES LBR_MDFeInfPag(LBR_MDFeInfPag_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:02:24 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeReboque', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:02:24','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802426
;

ALTER TABLE LBR_MDFeReboque ADD CONSTRAINT LBRMDFe_LBRMDFeReboque FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:02:33 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeSeg', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:02:33','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802617
;

ALTER TABLE LBR_MDFeSeg ADD CONSTRAINT LBRMDFe_LBRMDFeSeg FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:02:42 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeValePed', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:02:42','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802529
;

ALTER TABLE LBR_MDFeValePed ADD CONSTRAINT LBRMDFe_LBRMDFeValePed FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:02:51 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFeEvento_LBRMDFeXML', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:02:51','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802686
;

ALTER TABLE LBR_MDFeXML ADD CONSTRAINT LBRMDFeEvento_LBRMDFeXML FOREIGN KEY (LBR_MDFeEvento_ID) REFERENCES LBR_MDFeEvento(LBR_MDFeEvento_ID) DEFERRABLE INITIALLY DEFERRED
;

-- 8 de set. de 2026 15:03:00 BRT

UPDATE AD_Column SET FKConstraintName='LBRMDFe_LBRMDFeXML', FKConstraintType='N',
       Updated=TO_TIMESTAMP('2026-09-08 15:03:00','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100 WHERE AD_Column_ID=802685
;

ALTER TABLE LBR_MDFeXML ADD CONSTRAINT LBRMDFe_LBRMDFeXML FOREIGN KEY (LBR_MDFe_ID) REFERENCES LBR_MDFe(LBR_MDFe_ID) DEFERRABLE INITIALLY DEFERRED
;


-- 2. C_DocType_ID volta a ser opcional

-- 8 de set. de 2026 15:03:09 BRT

UPDATE AD_Column SET IsMandatory='N', Updated=TO_TIMESTAMP('2026-09-08 15:03:09','YYYY-MM-DD HH24:MI:SS'), UpdatedBy=100
 WHERE ColumnName='C_DocType_ID'
   AND AD_Table_ID=(SELECT AD_Table_ID FROM AD_Table WHERE TableName='LBR_MDFe')
;

ALTER TABLE LBR_MDFe MODIFY C_DocType_ID NULL
;


-- 3. DocBaseType 'MDF' na AD_Reference 183

-- 8 de set. de 2026 15:03:18 BRT

INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Value,Name,Description,EntityType,AD_Ref_List_UU)
SELECT 800530,183,0,0,'Y',TO_TIMESTAMP('2026-09-08 15:03:18','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2026-09-08 15:03:18','YYYY-MM-DD HH24:MI:SS'),100,'MDF','Manifesto Eletronico de Documentos Fiscais','DocBaseType do MDF-e, modelo 58','LBR','01a082cd-9bc0-738c-a186-48572d79e3aa'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM AD_Ref_List WHERE AD_Reference_ID=183 AND Value='MDF')
;
