#Adempiere
#Fri Jun 05 12:36:41 BRT 2026
CDate=xyz2026-06-05 12\:36\:38.696
Warning=Do_not_change_any_of_the_data_as_they_will_have_undocumented_side_effects.
WarningD=Einstellungen_nicht_aendern,_da_diese_undokumentierte_Nebenwirkungen_haben.
UITheme=xyzAdempiere Theme
StorePassword=xyzN
AutoCommit=xyzY
ShowAcct=xyzY
Language=xyzpt_BR
TraceFile=xyzN
CacheWindow=xyzY
PrintPreview=xyzN
ValidateConnectionOnStartup=xyzN
UILookFeel=xyzAdempiere
ShowTrl=xyzN
TempDir=xyz/tmp
AutoNew=xyzN
ApplicationUserID=xyzGardenAdmin
LoadTabMetaDataBackground=xyzN
SingleInstancePerWindow=xyzN
Charset=xyzUTF-8
DataSource=xyzjava\:adempiereDB
OpenWindowMaximized=xyzN
AutoLogin=xyzN
AdempiereSys=xyzN
TraceLevel=xyzWARNING
LogMigrationScript=xyzN
