package org.idempierelbr.openitems.process;

import org.compiere.process.ProcessCall;

public interface ICNABFactory {
	/**
	 * Create new process instance
	 * @param routingNo bank routing number
	 * @param isReturn true if the file is generated by the bank
	 * @return new process instance
	 */
	public ProcessCall newProcessInstance(String routingNo, boolean isReturn);
}
